---
- name: install dependencies
  yum:
    name: ['epel-release','curl']
    state: installed

- name: Add repository 'remi-repo'
  command: rpm -ih http://rpms.famillecollet.com/enterprise/remi-release-7.rpm creates=/etc/yum.repos.d/remi.repo

- name: install php7.3
  yum: name={{ item }} enablerepo=epel,remi,remi-php{{ centos_php_version }} state=installed
  with_items:
    - php{{ centos_php_version }}
    - php{{ centos_php_version }}-php-mcrypt
    - php{{ centos_php_version }}-php-mbstring
    - php{{ centos_php_version }}-php-fpm
    - php{{ centos_php_version }}-php-gd
    - php{{ centos_php_version }}-php-xml
    - php{{ centos_php_version }}-php-pdo
    - php{{ centos_php_version }}-php-zip
    - php{{ centos_php_version }}-php-devel
    - php{{ centos_php_version }}-php-geos
    - php{{ centos_php_version }}-php-gmp
    - php{{ centos_php_version }}-php-imap
    - php{{ centos_php_version }}-php-mysqlnd
    - php{{ centos_php_version }}-php-mbstring
    - php{{ centos_php_version }}-php-pecl-apcu
    - php{{ centos_php_version }}-php-common
    - php{{ centos_php_version }}-php-json
    - php{{ centos_php_version }}-php-cli
    - php{{ centos_php_version }}-php-intl
    - php{{ centos_php_version }}-php-pecl-redis5
    - php{{ centos_php_version }}-php-soap
    - php{{ centos_php_version }}-php-bcmath
    - php{{ centos_php_version }}-php-opcache
    - php{{ centos_php_version }}-php-pecl-mongodb
    - php{{ centos_php_version }}-php-pecl-mysql
    - php{{ centos_php_version }}-php-bz2
    - php{{ centos_php_version }}-php-readline
    - php{{ centos_php_version }}-php-sqlite3
    - openssl-devel
    - cyrus-sasl-devel

- name : link env file
  command: ln -s /opt/remi/php{{ centos_php_version }}/enable /etc/profile.d/php{{ centos_php_version }}.sh creates=/etc/profile.d/php{{ centos_php_version }}.sh

#Composer
- name: Download and install Composer in Centos
  shell: curl -sS https://getcomposer.org/installer | php{{ centos_php_version }}
  become: yes

- name: Move composer.phar file to usr/local/bin/composer
  shell: mv composer.phar /usr/local/bin/composer

#Configurations
- name: create phpfpm log is enabled
  file:
    path: "{{ log_path }}"
    mode: 0755
    state: directory

- name: create phpfpm log is enabled
  changed_when: false
  file:
    path: "{{ item }}"
    mode: 0644
    state: touch
  with_items:
    - "{{ log_path }}/php-pool-upstream-error.log"
    - "{{ log_path }}/php-ini-error.log"
    - "{{ log_path }}/php-pool-www-error.log"

- name: transfer pool.d php-fpm configuration
  template:
    src: "{{ item }}"
    dest: "{{ php_fpm_dir_cent }}/{{ item | basename }}"
    force: true
  with_fileglob:
    - ../templates/config/pool.d/*.*

- name: transfer mods-available php configuration
  template:
    src: "{{ item }}"
    dest: "{{ php_dir_cent }}/{{ item | basename }}"
    force: true
  with_fileglob:
    - ../templates/config/mods-available/*.ini

- name: transfer php.ini php-fpm configuration
  template:
    src: config/php.ini
    dest: "{{ php_fpm_dir_cent }}/php.ini"
    force: true
