---
- import_tasks: ubuntu.yml
  when:
    - state == "present"
    - ansible_facts['distribution'] == "Ubuntu"
    
- import_tasks: amazonlinux.yml
  when:
    - state == "present"
    - ansible_facts['distribution'] == "Amazon"

- import_tasks: centos.yml
  when:
    - state == "present"
    - ansible_facts['distribution'] == "CentOS"
